fix: homebrew coudnt installed5

diff --git a/install b/install
--- a/install
+++ b/install
@@ -135,31 +135,32 @@ xcode_download() {
     fi
 }
 
-# # install brew
-# brew_install() {
-#     install brew printf '\n' | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" \
-#     & $BREW_PID=$!
-#     wait $BREW_PID
-#     if [ `grep 'eval "$(/opt/homebrew/bin/brew shellenv)"' ~/.zprofile | wc -l` -eq 0 ]; then
-#         echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
-#     fi
-#     eval "$(/opt/homebrew/bin/brew shellenv)"
-# }
-
-# install brew -------- temporary
+# install brew
 brew_install() {
-    if ! has brew; then
-        # Use yes to automatically answer yes to prompts
-        yes | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" < /dev/null
-        if [ $? -ne 0 ]; then
-            error "Failed to install Homebrew."
-        fi
+    install brew NONINTERACTIVE=1 | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" < /dev/null
+    if [ $? -ne 0 ]; then
+        error "Failed to install Homebrew."
     fi
-    if [ "$(grep 'eval "$(/opt/homebrew/bin/brew shellenv)"' ~/.zprofile | wc -l)" -eq 0 ]; then
+    if [ `grep 'eval "$(/opt/homebrew/bin/brew shellenv)"' ~/.zprofile | wc -l` -eq 0 ]; then
         echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
     fi
     eval "$(/opt/homebrew/bin/brew shellenv)"
 }
+
+# # install brew -------- temporary
+# brew_install() {
+#     if ! has brew; then
+#         # Use yes to automatically answer yes to prompts
+#         yes | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" < /dev/null
+#         if [ $? -ne 0 ]; then
+#             error "Failed to install Homebrew."
+#         fi
+#     fi
+#     if [ "$(grep 'eval "$(/opt/homebrew/bin/brew shellenv)"' ~/.zprofile | wc -l)" -eq 0 ]; then
+#         echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
+#     fi
+#     eval "$(/opt/homebrew/bin/brew shellenv)"
+# }
 
 # install git and setting gitconfig and sshkey with user input
 gitconfig_set() {
